let platform = ''
// #ifdef  MP-WEIXIN
platform = 'mini'
// #endif
// #ifdef  MP-ALIPAY
platform = 'ali'
// #endif
// #ifdef  MP-BAIDU
platform = 'baidu'
// #endif
// #ifdef  MP-TOUTIAO	
platform = 'toutiao'
// #endif
// #ifdef  MP-KUAISHOU	
platform = 'kuaishou'
// #endif
// #ifdef  H5
const isWechat = () => {
	return String(navigator.userAgent.toLowerCase().match(/MicroMessenger/i)) == "micromessenger";
}
const isAlipay = () => {
	return /AlipayClient|AliApp\(AP/i.test(navigator.userAgent.toLowerCase())
}
platform = isWechat() ? 'wechat' : isAlipay() ? 'alih5' : 'h5'
// #endif
let t = '/channelApi/',
	api = {
		platform,
		config: t + 'config',
		login: t + 'wechat/login',
		emaillogin: t + 'emaillogin',
		resetPassword: t + 'resetPassword',
		emailRegister: t + 'emailRegister',
		facebookLogin: t + 'facebookLogin',
		lineLogin: t + 'lineLogin',
		checkLineCode: t + 'checkLineCode',
		profix: t + 'profix',
		wrg: t + 'wechat/register',
		jm: t + 'wechat/decrypt',
		xgyh: t + 'profix/edit',
		wau: t + 'wechat/authorizationUrl',
		sms: t + 'sendSms',
		wcl: t + 'wechat/wechatLogin',
		pay: t + 'pay',
		orderPay: t + 'pay',
		wxjs: t + 'jssdk',
		gxmb: t + 'profix/mobile',
		updateBirthday: t + 'updateBirthday',
		mrmd: t + 'store/default',
		zbtdz: t + 'region/address',
		dplb: t + 'store',
		region: t + 'region',
		goods: t + 'goods',
		xggwc: t + 'cart',
		wdgwc: t + 'cart',
		qkgwc: t + 'cart/clear',
		wdshdz: t + 'address',
		checkout: t + 'cart/checkout',
		wmxd: t + 'order',
		qxdd: t + 'order/close',
		sqtk: t + 'order/refundApply',
		wdxddz: t + 'cart/address',
		cMap: t + 'configFormMap',
		layout: t + 'drag',
		dplbsc: t + 'collect/store',
		storesc: t + 'collect/store',
		wmmbxx: t + 'messageConfig',
		gglb: t + 'ad',
		wwdd: t + 'order/backlog',
		qrsh: t + 'order/complete',
		czgz: t + 'storeValue',
		yemx: t + 'accountLog',
		jfmx: t + 'integralLog',
		lqzx: t + 'coupon',
		mycp: t + 'my/coupon',
		cCode: t + 'coupon/qrcode',
		bzzx: t + 'helpers',
		yhqzz: t + 'couponRegift',
		confirmGift: t + 'couponRegift/confirmGift',
		getGift: t + 'couponRegift/getGift',
		jszz: t + 'couponRegift/receive',
		xkzx: t + 'giftBig',
		wc: t + 'windowCoupon',
		dhm: t + 'exchangeCode/coupon',
		dhb: t + 'exchangeCode/balance',
		cPrice: t + 'cart/price',
		hydj: t + 'vipCard',
		qrCode: t + 'qrcode',
		mdxx: t + 'personPay',
		tsczxq: t + 'inStore/table',
		ingwc: t + 'inStore/cart',
		inqkgwc: t + 'inStore/cart/clear',
		incheck: t + 'inStore/cart/checkout',
		sPrice: t + 'inStore/cart/price',
		ingoods: t + 'inStore/goods',
		inPeople: t + 'inStore/table',
		inOrder: t + 'inStore/order',
		call: t + 'inStore/table/callWaiter',
		insqxdd: t + 'inStore/order/close',
		spss: t + 'goods/search',
		insqtk: t + 'inStore/order/refundApply',
		inspss: t + 'inStore/goods/search',
		inwcdd: t + 'inStore/order/complete',
		jfscfl: t + 'pointsMallClassification',
		jfsplb: t + 'pointsMall',
		pMallOut: t + 'pointsMall/checkout',
		lqhd: t + 'couponActivity',
		ppcheckout: t + 'personPay/checkout',
		wdqdsj: t + 'signIn',
		jfdd: t + 'pointsMallOrder',
		jfsctk: t + 'pointsMallOrder/refundApply',
		jfscqx: t + 'pointsMallOrder/close',
		jfqrsh: t + 'pointsMallOrder/complete',
		smsLogin: t + 'sendSms',
		sendCode: t + 'sendCode',
		sendRegisterCode: t + 'sendRegisterCode',
		mobileLogin: t + 'mobileLogin',
		bindmobile: t + 'bindmobile',
		goodsPackAll: t + 'inStore/cart/packAll',
		pdcz: t + 'queuingUp/table',
		pdxd: t + 'queuingUp',
		couponPack: t + 'couponPack',
		couponPackOrder: t + 'couponPackOrder',
		birthday: t + 'birthday',
		yyxx: t + 'tableReserve',
		yycj: t + 'tableReserveOrder',
		yycheck: t + 'tableReserve/checkout',
		ldx: t + 'oldWithNew/partyA',
		ldxb: t + 'oldWithNew/partyB',
		ldxhb: t + 'oldWithNew/shear',
		ldxjla: t + 'oldWithNew/recordA',
		ldxjlb: t + 'oldWithNew/recordB',
		startOrder: t + 'inStore/order/startOrder',
		gCategory: t + 'goods/category',
		gInCategory: t + 'inStore/goods/category',
		pQuery: t + 'pay/query',
		logout: t + 'logout',
		wordCoupon: t + 'wordCoupon',
		dOrder: t + 'drinks/order',
		dLog: t + 'drinks/log',
		equityCard: t + 'equityCard',
		equityCardOrder: t + 'equityCardOrder',
		myCard: t + 'equityCardOrder/myCard',
		distributionAD: t + 'partner',
		partnerShear: t + 'partner/share',
		partnerOrder: t + 'partner/order',
		partnerDownline: t + 'partner/downline',
		feedback: t + 'order/feedback',
		gettastingmenu: t + 'order/gettastingmenu',
	};
export default api